export const theme = {
  colors: {
    background: '#F5F5F5',
    surface: '#FFFFFF',
    primary: '#1A1A2E',
    accent: '#4A90D9',
    danger: '#E8734A',
    success: '#2ECC71',
    warning: '#C0392B',
    text: '#1A1A2E',
    textSecondary: '#555555',
    textMuted: '#888888',
    textSoft: '#666666',
    border: '#CCCCCC',
    overlay: 'rgba(0,0,0,0.45)',
    white: '#FFFFFF',
    black: '#000000',
  },
  radius: {
    sm: 8,
    md: 10,
    lg: 12,
    xl: 16,
    pill: 26,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 28,
  },
  shadow: {
    card: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
    },
    modal: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 8,
    },
  },
} as const;
